# Use Postgres as base image
FROM postgres

# Copy the SQL scripts for initializing the DB to the Postgres container
ADD schema /etc/rocket

# Add the schema to Postgres' initdb.d so the DB is set up automatically when
# the container starts
ADD schema/tables.sql /docker-entrypoint-initdb.d/init.sql
