version: '3'

services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .db.env

  rocket:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: rocket
    volumes:
      - "/etc/ssl/certs:/etc/ssl/certs"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
    env_file:
      - .app.env