version: '3'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .db.env

  rocket:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file:
      - .app.env